apiVersion: postgresql.example.com/v1alpha1
kind: PgRestore
metadata:
  name: example-pgrestore
spec:
  image: applicadb/postgres-python
  serviceIp: service.psql.svc.cluster.local
  dbName: students-02-03-2020.sql;supermarket-03-03-2020.sql
  postgresDb: postgresdb
  postgresUser: postgresadmin
  postgresPassword: admin123
  backupFile: data.sql


